
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS BEGIN DOC END LB RB SECTION TEXT TITLEdoc : BEGIN LB DOC RB content END LB DOC RBcontent : title abs sectionstitle : TITLE LB TEXT RBabs : BEGIN LB ABS RB TEXT END LB ABS RBsections : sections section\n                | sectionsection : SECTION LB TEXT RB TEXT'
    
_lr_action_items = {'BEGIN':([0,6,22,],[1,9,-3,]),'LB':([1,7,9,12,16,29,],[3,11,13,18,21,31,]),'TITLE':([5,],[7,]),'DOC':([3,18,],[4,23,]),'SECTION':([10,14,15,20,30,33,],[16,-6,16,-5,-7,-4,]),'ABS':([13,31,],[19,32,]),'RB':([4,17,19,23,25,32,],[5,22,24,26,28,33,]),'TEXT':([11,21,24,28,],[17,25,27,30,]),'END':([8,14,15,20,27,30,],[12,-6,-2,-5,29,-7,]),'$end':([2,26,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'title':([5,],[6,]),'doc':([0,],[2,]),'section':([10,15,],[14,20,]),'content':([5,],[8,]),'abs':([6,],[10,]),'sections':([10,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doc","S'",1,None,None,None),
  ('doc -> BEGIN LB DOC RB content END LB DOC RB','doc',9,'p_doc','latex_parse3.py',70),
  ('content -> title abs sections','content',3,'p_content','latex_parse3.py',76),
  ('title -> TITLE LB TEXT RB','title',4,'p_title','latex_parse3.py',84),
  ('abs -> BEGIN LB ABS RB TEXT END LB ABS RB','abs',9,'p_abs','latex_parse3.py',91),
  ('sections -> sections section','sections',2,'p_sections','latex_parse3.py',97),
  ('sections -> section','sections',1,'p_sections','latex_parse3.py',98),
  ('section -> SECTION LB TEXT RB TEXT','section',5,'p_section','latex_parse3.py',108),
]
