
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ABS AUTHOR BEGIN DOC END ITEM ITEMIZE LB RB SECTION SUBSECTION TEXT TITLEdoc : BEGIN LB DOC RB content END LB DOC RBcontent : title author abs sections itemizetitle : TITLE LB TEXT RBauthor : AUTHOR LB TEXT RBabs : BEGIN LB ABS RB TEXT END LB ABS RBsections : sections section\n                | sectionsection : SECTION LB TEXT RB TEXTsection : section subsection\n                | subsection\n    subsection : SUBSECTION LB TEXT RB TEXT\n    itemize : BEGIN LB ITEMIZE RB items END LB ITEMIZE RB TEXTitems : items item\n                | item\n        item : ITEM TEXT'
    
_lr_action_items = {'BEGIN':([0,10,19,20,22,29,31,35,45,46,],[2,15,30,-7,-10,-6,-9,-4,-8,-11,]),'$end':([1,27,],[0,-1,]),'LB':([2,8,9,11,15,21,23,30,47,52,],[3,12,13,16,24,32,33,36,51,56,]),'DOC':([3,13,],[4,18,]),'RB':([4,17,18,25,34,37,38,40,55,58,],[5,26,27,35,39,41,42,44,57,59,]),'TITLE':([5,],[8,]),'END':([6,28,43,48,49,53,54,60,],[9,-2,47,52,-14,-13,-15,-12,]),'AUTHOR':([7,26,],[11,-3,]),'TEXT':([12,16,32,33,39,41,42,50,59,],[17,25,37,38,43,45,46,54,60,]),'SECTION':([14,19,20,22,29,31,45,46,57,],[21,21,-7,-10,-6,-9,-8,-11,-5,]),'SUBSECTION':([14,19,20,22,29,31,45,46,57,],[23,23,23,-10,23,-9,-8,-11,-5,]),'ABS':([24,51,],[34,55,]),'ITEMIZE':([36,56,],[40,58,]),'ITEM':([44,48,49,53,54,],[50,50,-14,-13,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'doc':([0,],[1,]),'content':([5,],[6,]),'title':([5,],[7,]),'author':([7,],[10,]),'abs':([10,],[14,]),'sections':([14,],[19,]),'section':([14,19,],[20,29,]),'subsection':([14,19,20,29,],[22,22,31,31,]),'itemize':([19,],[28,]),'items':([44,],[48,]),'item':([44,48,],[49,53,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> doc","S'",1,None,None,None),
  ('doc -> BEGIN LB DOC RB content END LB DOC RB','doc',9,'p_doc','CH11.py',80),
  ('content -> title author abs sections itemize','content',5,'p_content','CH11.py',87),
  ('title -> TITLE LB TEXT RB','title',4,'p_title','CH11.py',97),
  ('author -> AUTHOR LB TEXT RB','author',4,'p_author','CH11.py',104),
  ('abs -> BEGIN LB ABS RB TEXT END LB ABS RB','abs',9,'p_abs','CH11.py',110),
  ('sections -> sections section','sections',2,'p_sections','CH11.py',117),
  ('sections -> section','sections',1,'p_sections','CH11.py',118),
  ('section -> SECTION LB TEXT RB TEXT','section',5,'p_section','CH11.py',130),
  ('section -> section subsection','section',2,'p_subsections','CH11.py',138),
  ('section -> subsection','section',1,'p_subsections','CH11.py',139),
  ('subsection -> SUBSECTION LB TEXT RB TEXT','subsection',5,'p_subsection','CH11.py',151),
  ('itemize -> BEGIN LB ITEMIZE RB items END LB ITEMIZE RB TEXT','itemize',10,'p_itemsize','CH11.py',171),
  ('items -> items item','items',2,'p_items','CH11.py',178),
  ('items -> item','items',1,'p_items','CH11.py',179),
  ('item -> ITEM TEXT','item',2,'p_item','CH11.py',190),
]
