
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "NUMBER PRINT VARIABLEprogram : statementsstatements : statements statement\n                  | statement statement : assignment\n                  | operation\n                  | printassignment : VARIABLE '=' NUMBERoperation : VARIABLE '=' VARIABLE '+' VARIABLE\n                 | VARIABLE '=' VARIABLE '-' VARIABLEprint : PRINT '(' VARIABLE ')' "
    
_lr_action_items = {')':([12,],[15,]),'(':([2,],[10,]),'+':([13,],[17,]),'-':([13,],[16,]),'NUMBER':([11,],[14,]),'PRINT':([0,1,3,6,7,8,9,14,15,18,19,],[2,2,-4,-3,-6,-5,-2,-7,-10,-9,-8,]),'VARIABLE':([0,1,3,6,7,8,9,10,11,14,15,16,17,18,19,],[4,4,-4,-3,-6,-5,-2,12,13,-7,-10,18,19,-9,-8,]),'=':([4,],[11,]),'$end':([1,3,5,6,7,8,9,14,15,18,19,],[-1,-4,0,-3,-6,-5,-2,-7,-10,-9,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'assignment':([0,1,],[3,3,]),'program':([0,],[5,]),'statement':([0,1,],[6,9,]),'print':([0,1,],[7,7,]),'operation':([0,1,],[8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','py_yacc.py',16),
  ('statements -> statements statement','statements',2,'p_statements','py_yacc.py',22),
  ('statements -> statement','statements',1,'p_statements','py_yacc.py',23),
  ('statement -> assignment','statement',1,'p_statement','py_yacc.py',33),
  ('statement -> operation','statement',1,'p_statement','py_yacc.py',34),
  ('statement -> print','statement',1,'p_statement','py_yacc.py',35),
  ('assignment -> VARIABLE = NUMBER','assignment',3,'p_assignment','py_yacc.py',41),
  ('operation -> VARIABLE = VARIABLE + VARIABLE','operation',5,'p_operation','py_yacc.py',50),
  ('operation -> VARIABLE = VARIABLE - VARIABLE','operation',5,'p_operation','py_yacc.py',51),
  ('print -> PRINT ( VARIABLE )','print',4,'p_print','py_yacc.py',56),
]
