
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ELSE END FEWER GREATER ID IF LBRACKET LPAREN MINUS NUMBER PLUS RBRACKET RPARENterm : factor PLUS factor\n                | factor MINUS factorterm : term ENDterm : ID ID ASSIGN factorexpression : termterm : factorfactor : NUMBERexpression : ID ASSIGN NUMBERBOOL : expression GREATER NUMBER\n                | expression FEWER NUMBERBOOLs : LPAREN BOOL RPARENfactor : BOOLsterm : IF expression LBRACKET expression RBRACKET ELSE LBRACKET expression RBRACKET '
    
_lr_action_items = {'ID':([0,3,4,7,14,20,32,],[3,11,14,14,11,14,14,]),'IF':([0,4,7,20,32,],[4,4,4,4,4,]),'NUMBER':([0,4,7,9,10,19,20,21,23,24,32,],[5,5,5,5,5,5,5,27,28,29,5,]),'LPAREN':([0,4,7,9,10,19,20,32,],[7,7,7,7,7,7,7,7,]),'$end':([1,2,5,6,8,17,18,22,25,34,],[0,-6,-7,-12,-3,-1,-2,-11,-4,-13,]),'END':([1,2,5,6,8,13,17,18,22,25,34,],[8,-6,-7,-12,-3,8,-1,-2,-11,-4,-13,]),'PLUS':([2,5,6,22,],[9,-7,-12,-11,]),'MINUS':([2,5,6,22,],[10,-7,-12,-11,]),'LBRACKET':([2,5,6,8,12,13,17,18,22,25,27,31,34,],[-6,-7,-12,-3,20,-5,-1,-2,-11,-4,-8,32,-13,]),'GREATER':([2,5,6,8,13,16,17,18,22,25,27,34,],[-6,-7,-12,-3,-5,23,-1,-2,-11,-4,-8,-13,]),'FEWER':([2,5,6,8,13,16,17,18,22,25,27,34,],[-6,-7,-12,-3,-5,24,-1,-2,-11,-4,-8,-13,]),'RBRACKET':([2,5,6,8,13,17,18,22,25,26,27,33,34,],[-6,-7,-12,-3,-5,-1,-2,-11,-4,30,-8,34,-13,]),'ASSIGN':([11,14,],[19,21,]),'RPAREN':([15,28,29,],[22,-9,-10,]),'ELSE':([30,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,4,7,20,32,],[1,13,13,13,13,]),'factor':([0,4,7,9,10,19,20,32,],[2,2,2,17,18,25,2,2,]),'BOOLs':([0,4,7,9,10,19,20,32,],[6,6,6,6,6,6,6,6,]),'expression':([4,7,20,32,],[12,16,26,33,]),'BOOL':([7,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> term","S'",1,None,None,None),
  ('term -> factor PLUS factor','term',3,'p_expression','ch6.py',32),
  ('term -> factor MINUS factor','term',3,'p_expression','ch6.py',33),
  ('term -> term END','term',2,'p_state_match','ch6.py',42),
  ('term -> ID ID ASSIGN factor','term',4,'p_expr_assign','ch6.py',49),
  ('expression -> term','expression',1,'p_expression_term','ch6.py',54),
  ('term -> factor','term',1,'p_term_factor','ch6.py',59),
  ('factor -> NUMBER','factor',1,'p_factor_num','ch6.py',64),
  ('expression -> ID ASSIGN NUMBER','expression',3,'p_assign_assign','ch6.py',70),
  ('BOOL -> expression GREATER NUMBER','BOOL',3,'p_compare','ch6.py',76),
  ('BOOL -> expression FEWER NUMBER','BOOL',3,'p_compare','ch6.py',77),
  ('BOOLs -> LPAREN BOOL RPAREN','BOOLs',3,'p_factor_expr','ch6.py',87),
  ('factor -> BOOLs','factor',1,'p_BOOL_fac','ch6.py',91),
  ('term -> IF expression LBRACKET expression RBRACKET ELSE LBRACKET expression RBRACKET','term',9,'p_logic_judge','ch6.py',95),
]
