
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ASSIGN ELSE END FEWER GREATER ID IF INT LBRACKET LPAREN NUMBER RBRACKET RPARENexpression : SID '+' factor\n                | SID '-' factorexpression : expression END SID : INT ID ASSIGN NUMBER\n                | ID ASSIGN expression\n    expression : factorfactor : NUMBERfactor : SIDBOOL : expression GREATER NUMBER\n                | expression FEWER NUMBERjudge : LPAREN BOOL RPARENexpression : IF judge LBRACKET expression RBRACKET ELSE LBRACKET expression RBRACKET "
    
_lr_action_items = {'IF':([0,12,14,18,32,],[4,4,4,4,4,]),'INT':([0,9,10,12,14,18,32,],[5,5,5,5,5,5,5,]),'ID':([0,5,9,10,12,14,18,32,],[6,13,6,6,6,6,6,6,]),'NUMBER':([0,9,10,12,14,18,21,25,26,32,],[7,7,7,7,7,7,27,29,30,7,]),'$end':([1,2,3,7,8,15,16,17,22,27,34,],[0,-8,-6,-7,-3,-8,-1,-2,-5,-4,-12,]),'END':([1,2,3,7,8,15,16,17,20,22,23,27,33,34,],[8,-8,-6,-7,-3,-8,-1,-2,8,8,8,-4,8,-12,]),'+':([2,3,7,8,15,16,17,22,27,34,],[9,-6,-7,-3,-8,-1,-2,-5,-4,-12,]),'-':([2,3,7,8,15,16,17,22,27,34,],[10,-6,-7,-3,-8,-1,-2,-5,-4,-12,]),'GREATER':([2,3,7,8,15,16,17,20,22,27,34,],[-8,-6,-7,-3,-8,-1,-2,25,-5,-4,-12,]),'FEWER':([2,3,7,8,15,16,17,20,22,27,34,],[-8,-6,-7,-3,-8,-1,-2,26,-5,-4,-12,]),'RBRACKET':([2,3,7,8,15,16,17,22,23,27,33,34,],[-8,-6,-7,-3,-8,-1,-2,-5,28,-4,34,-12,]),'LPAREN':([4,],[12,]),'ASSIGN':([6,13,],[14,21,]),'LBRACKET':([11,24,31,],[18,-11,32,]),'RPAREN':([19,29,30,],[24,-9,-10,]),'ELSE':([28,],[31,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,12,14,18,32,],[1,20,22,23,33,]),'SID':([0,9,10,12,14,18,32,],[2,15,15,2,2,2,2,]),'factor':([0,9,10,12,14,18,32,],[3,16,17,3,3,3,3,]),'judge':([4,],[11,]),'BOOL':([12,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> SID + factor','expression',3,'p_expression','ch6.py',32),
  ('expression -> SID - factor','expression',3,'p_expression','ch6.py',33),
  ('expression -> expression END','expression',2,'p_state_match','ch6.py',42),
  ('SID -> INT ID ASSIGN NUMBER','SID',4,'p_expr_assign','ch6.py',49),
  ('SID -> ID ASSIGN expression','SID',3,'p_expr_assign','ch6.py',50),
  ('expression -> factor','expression',1,'p_expre_factor','ch6.py',59),
  ('factor -> NUMBER','factor',1,'p_factor_num','ch6.py',64),
  ('factor -> SID','factor',1,'p_factor_ID','ch6.py',68),
  ('BOOL -> expression GREATER NUMBER','BOOL',3,'p_compare','ch6.py',76),
  ('BOOL -> expression FEWER NUMBER','BOOL',3,'p_compare','ch6.py',77),
  ('judge -> LPAREN BOOL RPAREN','judge',3,'p_factor_expr','ch6.py',87),
  ('expression -> IF judge LBRACKET expression RBRACKET ELSE LBRACKET expression RBRACKET','expression',9,'p_logic_judge','ch6.py',92),
]
