
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AVG BY FROM NAME NUMBER ORDER SELECT WHEREquery :  select select :   SELECT list FROM table WHERE lst ORDER BY list\n                | SELECT list FROM table WHERE lst\n                | SELECT list FROM table ORDER BY list\n                | SELECT list FROM table table : NAME  lst  : condition  condition : NAME '>' NUMBER\n                  | NAME '<' NUMBER\n                  | NAME '=' NUMBER\n                   list : '*'\n             | NAME\n            "
    
_lr_action_items = {'FROM':([4,5,6,],[-12,-11,7,]),'NAME':([3,7,10,15,24,],[4,8,12,4,4,]),'<':([12,],[17,]),'=':([12,],[16,]),'*':([3,15,24,],[5,5,5,]),'NUMBER':([16,17,18,],[21,22,23,]),'BY':([11,19,],[15,24,]),'>':([12,],[18,]),'WHERE':([8,9,],[-6,10,]),'ORDER':([8,9,13,14,21,22,23,],[-6,11,19,-7,-10,-9,-8,]),'SELECT':([0,],[3,]),'$end':([1,2,4,5,8,9,13,14,20,21,22,23,25,],[-1,0,-12,-11,-6,-5,-3,-7,-4,-10,-9,-8,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'list':([3,15,24,],[6,20,25,]),'lst':([10,],[13,]),'select':([0,],[1,]),'table':([7,],[9,]),'query':([0,],[2,]),'condition':([10,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select','query',1,'p_query','yacc.py',57),
  ('select -> SELECT list FROM table WHERE lst ORDER BY list','select',9,'p_select','yacc.py',62),
  ('select -> SELECT list FROM table WHERE lst','select',6,'p_select','yacc.py',63),
  ('select -> SELECT list FROM table ORDER BY list','select',7,'p_select','yacc.py',64),
  ('select -> SELECT list FROM table','select',4,'p_select','yacc.py',65),
  ('table -> NAME','table',1,'p_table','yacc.py',100),
  ('lst -> condition','lst',1,'p_lst','yacc.py',108),
  ('condition -> NAME > NUMBER','condition',3,'p_condition','yacc.py',117),
  ('condition -> NAME < NUMBER','condition',3,'p_condition','yacc.py',118),
  ('condition -> NAME = NUMBER','condition',3,'p_condition','yacc.py',119),
  ('list -> *','list',1,'p_list','yacc.py',129),
  ('list -> NAME','list',1,'p_list','yacc.py',130),
]
