
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "FROM NAME SELECT WHEREquery :  selectselect : SELECT list FROM table table : NAME list : '*'\n             | NAME"
    
_lr_action_items = {'*':([3,],[5,]),'FROM':([4,5,6,],[-5,-4,7,]),'NAME':([3,7,],[4,8,]),'SELECT':([0,],[3,]),'$end':([1,2,8,9,],[-1,0,-3,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[2,]),'list':([3,],[6,]),'select':([0,],[1,]),'table':([7,],[9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> select','query',1,'p_query','1.py',40),
  ('select -> SELECT list FROM table','select',4,'p_select','1.py',44),
  ('table -> NAME','table',1,'p_table','1.py',52),
  ('list -> *','list',1,'p_list','1.py',57),
  ('list -> NAME','list',1,'p_list','1.py',58),
]
